name: Run tests

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
  pull_request:
    branches:
    - main
env:
  MYSQL_ROOT_PASSWORD: test_password
  MYSQL_DATABASE: test_database
  MYSQL_USER: test_user
  MYSQL_PASSWORD: test_password
  MYSQL_HOST: 127.0.0.1

jobs:
  
  # macOS-tests:
  #   runs-on: self-hosted
  #   steps:
    
  #   - name: Checkout
  #     uses: actions/checkout@v4
    
  #   # - name: Cache
  #   #   uses: actions/cache@v3
  #   #   with:
  #   #     path: server/.build
  #   #     key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
  #   #     restore-keys: ${{ runner.os }}-spm-
    
  #   - name: Test
  #     env:
  #       MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  #       MYSQL_USER: ${{ secrets.MYSQL_USER }}
  #       MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
  #       MYSQL_DB: ${{ secrets.MYSQL_DB }}
  #     run: swift test --parallel --enable-code-coverage
  
  linux-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift:
          - 'swift:5.9'
          - 'swift:5.10'
        database:
          - mysql:8.2
    container:
      image: ${{ matrix.swift }}
    services:
      mysql:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_HOST: 127.0.0.1
          # MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Test
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: test_user
        MYSQL_PASS: test_password
        MYSQL_DB: test_database
      run: swift test --parallel --enable-code-coverage
